### ISSUE TITLE
unable to add keys to dictionaries

### ISSUE THREAD

**Issue by kristifristi** [walksanatora/HexTweaks#1]
both clerk's integration exaltation and clerk's distillation give an error
log can be found at [https://pastebin.com/M3MtZGHF](https://pastebin.com/M3MtZGHF)
-this is on the hexxycraft modpack

**Comment by walksanatora** [comment]
gonna need more context
What was the value you were trying to insert

**Comment by walksanatora** [comment]
still no clue, but try the latest update?

**Comment by walksanatora** [comment]
nope it broken

**Comment by walksanatora** [comment]
definetly fixed
